config/routes.rb
Rails.application.routes.draw do
  get 'all_turbo_users/index'

  devise_for :admins
  resources :companies
  resources :inventories do
  	collection { post :import }
end

 
  devise_for :users, :controllers => { registrations: 'registrations' }
  

  root "pages#home"
  get "about" => "pages#about"
  get "search" => "inventories#search"
  get "import" => "pages#import"
  get "import" => "pages#soon"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/inventory.rb
class Inventory < ApplicationRecord
	belongs_to :user

def self.import(file, user_id)
  allowed_attributes = [ "user_id", "id","description","part_number","price","created_at","updated_at", "alternate_part_number", "condition_code", "qty", "mfg_code", "serial_number", "part_comments"]
  spreadsheet = open_spreadsheet(file)
  header = spreadsheet.row(1)
  (2..spreadsheet.last_row).each do |i|
    row = Hash[[header, spreadsheet.row(i)].transpose]
    inventory = find_by_id(row["id"]) || new
    inventory.attributes = row.to_hash.select { |k,v| allowed_attributes.include? k }
    inventory.user_id = user_id
    inventory.save!
  end
end

def self.open_spreadsheet(file)
  case File.extname(file.original_filename)
  when ".csv" then Roo::CSV.new(file.path)
  when ".xls" then Excel.new(file.path, nil, :ignore)
  when ".xlsx" then Excelx.new(file.path, nil, :ignore)
  else raise "Unknown file type: #{file.original_filename}"
  end
end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :Inventories
end

app/controllers/all_turbo_users_controller.rb
class AllTurboUsersController < ApplicationController
  before_filter :authenticate_admin!, :except => [:show]
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:company_name, :company_street_number, :company_street_address, :company_street_address_2, :company_state, :company_zip, :company_phone, :company_sales_phone, :company_sales_email)
    end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :search]

  def index
    @inventories = Inventory.all.order("created_at DESC")
  end

  def show
  end

  def search
    if params[:part_number].present?
        @inventories = Inventory.order("created_at DESC").where("LOWER(part_number) like ?", "%%#{params[:part_number].downcase}%") if params[:part_number].present? 
    end
  end

  def new
    @inventory = current_user.Inventories.build
  end

  def edit
  end

  def create
    @inventory = current_user.Inventories.build(inventory_params)
    @inventory.user_id = current_user.id

    if @inventory.save
      redirect_to root_url, notice: 'Inventory was successfully created.'
    else
      render :new
    end
  end
  
  def update
    if @inventory.update(inventory_params)
      redirect_to root_url, notice: 'Inventory was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @inventory.destroy
    redirect_to search_path, notice: 'Inventory was successfully destroyed.'
  end

  def import
    Resque.enqueue(Inventorycsvimport, file: params[:file], user_id: current_user.id,)
    redirect_to root_url, notice: "Inventory import job started."
  end

  private

    def set_inventory
      @inventory = Inventory.find(params[:id])
    end

  def correct_user
    @inventory = current_user.Inventories.find_by(id: params[:id])
    redirect_to inventories_path, notice: "you are unable to edit another companies inventory" if @inventory.nil?
  end

    def inventory_params
      params.require(:inventory).permit(:description, :part_number, :alternate_part_number, :condition_code, :qty, :mfg_code, :serial_number, :part_comments, :price)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  end
  def about
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:company_name,:first_name, :last_name, :email, :password, :password_confirmation, :company_street_number, :company_street_address, :company_street_address_2, :company_state, :company_zip, :company_phone, :company_sales_phone, :company_sales_email, :company_comment)
  end

  def account_update_params
    params.require(:user).permit(:company_name,:first_name, :last_name, :email, :password, :password_confirmation, :current_password, :company_street_number, :company_street_address, :company_street_address_2, :company_state, :company_zip, :company_phone, :company_sales_phone, :company_sales_email, :company_comment)
  end
end

app/helpers/all_turbo_users_helper.rb
module AllTurboUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/all_turbo_users/index.html.erb
<h1>AllTurboUsers#index</h1>

<% @users = User.all %>
<% @users.each do |user| %>
  <%= user.email %><br/>
<% end %>

app/views/companies/_form.html.erb
<%= form_for(company) do |f| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :company_name %>
    <%= f.text_area :company_name %>
  </div>

  <div class="field">
    <%= f.label :company_street_number %>
    <%= f.text_field :company_street_number %>
  </div>

  <div class="field">
    <%= f.label :company_street_address %>
    <%= f.text_field :company_street_address %>
  </div>

  <div class="field">
    <%= f.label :company_street_address_2 %>
    <%= f.text_field :company_street_address_2 %>
  </div>

  <div class="field">
    <%= f.label :company_state %>
    <%= f.text_field :company_state %>
  </div>

  <div class="field">
    <%= f.label :company_zip %>
    <%= f.text_field :company_zip %>
  </div>

  <div class="field">
    <%= f.label :company_phone %>
    <%= f.text_field :company_phone %>
  </div>

  <div class="field">
    <%= f.label :company_sales_phone %>
    <%= f.text_field :company_sales_phone %>
  </div>

  <div class="field">
    <%= f.label :company_sales_email %>
    <%= f.text_field :company_sales_email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<table>
  <thead>
    <tr>
      <th>Company name</th>
      <th>Company street number</th>
      <th>Company street address</th>
      <th>Company street address 2</th>
      <th>Company state</th>
      <th>Company zip</th>
      <th>Company phone</th>
      <th>Company sales phone</th>
      <th>Company sales email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.company_name %></td>
        <td><%= company.company_street_number %></td>
        <td><%= company.company_street_address %></td>
        <td><%= company.company_street_address_2 %></td>
        <td><%= company.company_state %></td>
        <td><%= company.company_zip %></td>
        <td><%= company.company_phone %></td>
        <td><%= company.company_sales_phone %></td>
        <td><%= company.company_sales_email %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company name:</strong>
  <%= @company.company_name %>
</p>

<p>
  <strong>Company street number:</strong>
  <%= @company.company_street_number %>
</p>

<p>
  <strong>Company street address:</strong>
  <%= @company.company_street_address %>
</p>

<p>
  <strong>Company street address 2:</strong>
  <%= @company.company_street_address_2 %>
</p>

<p>
  <strong>Company state:</strong>
  <%= @company.company_state %>
</p>

<p>
  <strong>Company zip:</strong>
  <%= @company.company_zip %>
</p>

<p>
  <strong>Company phone:</strong>
  <%= @company.company_phone %>
</p>

<p>
  <strong>Company sales phone:</strong>
  <%= @company.company_sales_phone %>
</p>

<p>
  <strong>Company sales email:</strong>
  <%= @company.company_sales_email %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/inventories/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
    <img src="http://d3fwmhwfh9c00r.cloudfront.net/logonew1.png" width="300" height="50" class="img-responsive" alt="TurboLogo" />
<%= form_for(inventory) do |f| %>
  <% if inventory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

      <ul>
      <% inventory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :part_number %>
    <%= f.text_field :part_number, class: "form-control", required: true %>
  </div>

    <div class="form-group">
    <%= f.label :alternate_part_number %>
    <%= f.text_field :alternate_part_number, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= f.label :qty %>
    <%= f.number_field :qty, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :condition_code %>
    <%= f.text_field :condition_code, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :mfg_code %>
    <%= f.text_field :mfg_code, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :serial_number %>
    <%= f.text_field :serial_number, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :part_comments %>
    <%= f.text_area :part_comments, class: "form-control" %>
  </div>


  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/inventories/edit.html.erb
<%= render 'form', inventory: @inventory %>
<br>
  <div class="panel-footer">
 <%= link_to '<i class="glyphicon glyphicon-arrow-left"></i>'.html_safe, :back , class: 'btn btn-default' %>     <%= link_to '<i class="glyphicon glyphicon-search"></i>'.html_safe, search_path , class: 'btn btn-default' %>
</div>

app/views/inventories/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
    <img src="http://d3fwmhwfh9c00r.cloudfront.net/logonew1.png" width="300" height="50" class="img-responsive" alt="TurboLogo" />

    

<h1>Inventory</h1>

<br>

        <%= form_tag search_path, method: :get do %>
             <div class="field">
               
               <%= text_field_tag :part_number, params[:part_number], placeholder: "enter part number" %>
              <%= submit_tag "Search", name: nil, class: "btn btn-primary" %>
              
            </div>
        <% end %>

    <% unless @inventories.blank? %>
    
</div>
</div> 
<div class="table-responsive">    
<table class="table table-hover">

  <thead>
    <tr>
      <th>Company Name</th>
      <th>Part number</th>
      <th>Alt</th>
      <th>Description</th>
      <th>Qty</th>
      <th>Price</th>
      <th>Cond code</th>
      <th>Part comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inventories.each do |inventory| %>
      <tr>
        <td><%= inventory.user.company_name %> </td>
        <td><%= inventory.part_number %></td>
        <td><%= inventory.alternate_part_number %></td>
        <td><%= inventory.description %></td>
        <td><%= inventory.qty %></td>
        <td><%= inventory.price %></td>
        <td><%= inventory.condition_code %></td>
        <td><%= inventory.part_comments %></td>
        <td><%= link_to '<i class="glyphicon glyphicon-info-sign"></i>'.html_safe, inventory, class: 'btn btn-primary' %></td>
        <% if inventory.user == current_user %>
        <td><%= link_to '<i class="glyphicon glyphicon-pencil"></i>'.html_safe, edit_inventory_path(inventory), class: 'btn btn-warning' %></td>
        <td><%= link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe, inventory, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div> 
<% end %>

    
<br>
  <div class="panel-footer">
 <br>
</div>

app/views/inventories/new.html.erb
<h1>New Inventory</h1>

<%= render 'form', inventory: @inventory %>

<br>

<%= link_to '<i class="glyphicon glyphicon-arrow-left"></i>'.html_safe, :back , class: 'btn btn-default' %>     <%= link_to '<i class="glyphicon glyphicon-search"></i>'.html_safe, search_path , class: 'btn btn-default' %>

app/views/inventories/search.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
    <img src="http://d3fwmhwfh9c00r.cloudfront.net/logonew1.png" width="300" height="50" class="img-responsive" alt="TurboLogo" />

    

<h1>Inventory</h1>

<br>

        <%= form_tag search_path, method: :get do %>
             <div class="field">
               
               <%= text_field_tag :part_number, params[:part_number], placeholder: "enter part number" %>
              <%= submit_tag "Search", name: nil, class: "btn btn-primary" %>
              
            </div>
        <% end %>

    <% unless @inventories.blank? %>
    
</div>
</div> 
<div class="table-responsive">    
<table class="table table-hover">

  <thead>
    <tr>
      <th>Company Name</th>
      <th>Part number</th>
      <th>Alt</th>
      <th>Description</th>
      <th>Qty</th>
      <th>Price</th>
      <th>Cond code</th>
      <th>Part comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inventories.each do |inventory| %>
      <tr>
        <td><%= inventory.user.company_name %> </td>
        <td><%= inventory.part_number %></td>
        <td><%= inventory.alternate_part_number %></td>
        <td><%= inventory.description %></td>
        <td><%= inventory.qty %></td>
        <td><%= inventory.price %></td>
        <td><%= inventory.condition_code %></td>
        <td><%= inventory.part_comments %></td>
        <td><%= link_to '<i class="glyphicon glyphicon-info-sign"></i>'.html_safe, inventory, class: 'btn btn-primary' %></td>
        <% if inventory.user == current_user %>
        <td><%= link_to '<i class="glyphicon glyphicon-pencil"></i>'.html_safe, edit_inventory_path(inventory), class: 'btn btn-warning' %></td>
        <td><%= link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe, inventory, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div> 
<% end %>

    
<br>
  <div class="panel-footer">
 <br>
</div>

app/views/inventories/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
    <img src="http://d3fwmhwfh9c00r.cloudfront.net/logonew1.png" width="300" height="50" class="img-responsive" alt="TurboLogo" />
<p id="notice"><%= notice %></p>
<h2>Inventory Item Detail</h2>
</div>
</div>
<br>
<div class="panel-body">

<p>
  <strong>Company Contact:</strong>
</p>

<p>
  <h3><%= @inventory.user.company_name if @inventory.user.company_name  %></h3>
</p>

<p>
  <%= @inventory.user.company_comment if @inventory.user.company_comment  %>
</p>

<p>
  <%= @inventory.user.company_sales_email if @inventory.user.company_sales_email  %>
</p>

<p>
  <%= @inventory.user.company_sales_phone if @inventory.user.company_sales_phone  %>
</p>

<hr>

<p>
  <strong>Part number:</strong>
  <%= @inventory.part_number %>
</p>

<p>
  <strong>Alternate part number:</strong>
  <%= @inventory.alternate_part_number %>
</p>

<p>
  <strong>Description:</strong>
  <%= @inventory.description %>
</p>

<p>
  <strong>Qty:</strong>
  <%= @inventory.qty %>
</p>

<p>
  <strong>Price:</strong>
  <%= @inventory.price %>
</p>

<p>
  <strong>Condition code:</strong>
  <%= @inventory.condition_code %>
</p>

<p>
  <strong>Mfg code:</strong>
  <%= @inventory.mfg_code %>
</p>

<p>
  <strong>Serial number:</strong>
  <%= @inventory.serial_number %>
</p>

<p>
  <strong>Part comments:</strong>
  <%= @inventory.part_comments %>
</p>

</div>

<br>
  <div class="panel-footer">
 <%= link_to '<i class="glyphicon glyphicon-arrow-left"></i>'.html_safe, :back , class: 'btn btn-default' %>   <%=  link_to '<i class="glyphicon glyphicon-pencil"></i>'.html_safe, edit_inventory_path(@inventory), class: 'btn btn-default' %>  <%= link_to '<i class="glyphicon glyphicon-search"></i>'.html_safe, search_path , class: 'btn btn-default' %>

</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
<div class="container">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
       
       <% if user_signed_in? %>
      <a class="navbar-brand" href="/"> <%= current_user.company_name if current_user.company_name %></a>
      <% end %>
      
     
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <% else %>
        <li><%= link_to "Login", new_user_session_path, class: "nav navbar-nav navbar-right" %></li> 
        <li><%= link_to "Sign up", new_user_registration_path, class: "nav navbar-nav navbar-right" %></li>
        <% end %>
        <!-- <li><a href="#">About</a></li> -->

        <% if user_signed_in? %>

        
      </form>
          
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account <span class="caret"></span></a>
          <% end %>
          <ul class="dropdown-menu">
            <li><%= link_to "My Profile", edit_user_registration_path %></li>
            <li><%= link_to "Add Inventory", import_path %></li>
            
            <li role="separator" class="divider"></li>
            <% if user_signed_in? %>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
  </div><!-- /.container  -->
</nav>

app/views/layouts/_search.html.erb
<form class="form-inline">
  <div class="form-group">
    <div class="input-group">
      <input type="text" class="form-control" id="search_value" placeholder="search">
    </div>
  </div>
  <button type="submit" class="btn btn-primary">submit</button>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <%= favicon_link_tag 'http://d3fwmhwfh9c00r.cloudfront.net/favicon-16x16.png' %>
    <title>InventoryTurbo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>

	<%= render 'layouts/navbar' %>

  <div class="container">
    	<% flash.each do |name, msg | %>
    		<%= content_tag(:div,msg, class: "alert alert-info") %>
    	<% end %>
    	<%= yield %>

    </div>

  </body>
</html>

app/views/layouts/soon.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
    <img src="http://d3fwmhwfh9c00r.cloudfront.net/logonew1.png" width="300" height="50" class="img-responsive" alt="TurboLogo" />

    

<h1>Coming Soon</h1>

<br>
New feature coming soon!

<br>
</div> 


    
<br>
  <div class="panel-footer">
 <br>
</div>

app/views/pages/about.html.erb
<h1>about my page</h1>

<iframe src="https://player.vimeo.com/video/173270262?autoplay=1&title=0&byline=0&portrait=0" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

<p>work in progress</p>

app/views/pages/home.html.erb
<div class="jumbotron center">
		<img src="http://d3fwmhwfh9c00r.cloudfront.net/logonew1.png" class="img-responsive center-block" width="500" height="200" alt="TurboLogo" />
	<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
    

       



<br>

        <%= form_tag search_path, method: :get do %>
             <div class="field">
               
               <%= text_field_tag :part_number, params[:part_number], placeholder: "enter part number" %>
              <%= submit_tag "Search", name: nil, class: "btn btn-primary" %>
            </div>
        <% end %>

    <% unless @inventories.blank? %>
    
</div>
</div> 
<div class="table-responsive">   
<table class="table table-hover">

  <thead>
    <tr>
      <th>Company Name</th>
      <th>Part number</th>
      <th>Alt</th>
      <th>Description</th>
      <th>Qty</th>
      <th>Price</th>
      <th>Cond code</th>
      <th>Part comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inventories.each do |inventory| %>
      <tr>
        <td><%= inventory.user.company_name %> </td>
        <td><%= inventory.part_number %></td>
        <td><%= inventory.alternate_part_number %></td>
        <td><%= inventory.description %></td>
        <td><%= inventory.qty %></td>
        <td><%= inventory.price %></td>
        <td><%= inventory.condition_code %></td>
        <td><%= inventory.part_comments %></td>
        <td><%= link_to 'Details', inventory %></td>
        <% if inventory.user == current_user %>
        <td><%= link_to 'Edit', edit_inventory_path(inventory) %></td>
        <td><%= link_to 'Delete', inventory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div> 
<% end %>

    
<br>
 
</div>

app/views/pages/import.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
    <img src="http://d3fwmhwfh9c00r.cloudfront.net/logonew1.png" width="300" height="50" class="img-responsive" alt="TurboLogo" />

<h2>Add Inventory</h2>
</div>
</div>

<div class="panel-body">
 <br>
 <h3>csv upload</h3>

<a href="https://inventoryturbo.zendesk.com/hc/en-us/articles/223178447-How-to-upload-inventory">Click here for upload instructions and sampe csv file</a> </p>

<%= form_tag import_inventories_path, multipart: true do %>
  <%= file_field_tag :file %>
  <br>
  <%= submit_tag "Import", name: nil, class: "btn btn-primary" %>

  
 <br>
 <hr>
  
  <h3>manually add a single part</h3>
  
  <a class="btn btn-primary" href="inventories/new" role="button">add a part</a>
  </div>
  <br>
<% end %>
  <div class="panel-footer">
 <%= link_to '<i class="glyphicon glyphicon-arrow-left"></i>'.html_safe, :back , class: 'btn btn-default' %>     <%= link_to '<i class="glyphicon glyphicon-search"></i>'.html_safe, search_path , class: 'btn btn-default' %>
</div>